### ISSUE TITLE
[PE-D] Dashboard overflowing without ability to scroll

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103-F09-3/tp#329]
![image.png](https://raw.githubusercontent.com/waynetee/ped/main/files/014a6446-35e0-4c0c-a1de-e29f8f0c18cd.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: waynetee/ped#6

**Comment by AllardQuek** [comment]
Proposed solution: Limit number of labs to 10 (since target users are CS2100 Lab TAs, very unlikely the user will need more than 10 labs)
