### ISSUE TITLE
[CodeCov] UI Components

### ISSUE THREAD

**Issue by reddevil1313** [AY2122S1-CS2103-F09-3/tp#335]

**Comment by ZhaoPeiduo** [comment]
There are already test cases for classes without javafx-related code ie `UiPart` and `CommandHistory`.

As for the rest of the classes under ui, I considered using testfx, but there seems to be some conflicts between CI and testfx test cases (see [\#363](https://github.com/nus-cs2103-AY2122S1/forum/issues/363) in forum).

Does anyone has any suggestions on how to test classes involving javafx without using testfx?
