### ISSUE TITLE
[PE-D] UG - Quick Start Screenshot Not Helpful

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103-F09-3/tp#347]
Words on screenshot in Quick Start section are too small, too much empty spaces and not helpful for the reader.

![Screenshot 2021-10-29 at 10.30.47 PM.png](https://raw.githubusercontent.com/mslevis/ped/main/files/fcf7c61f-a4ec-4bec-81c6-98fa8c141efc.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: mslevis/ped#6

**Comment by AllardQuek** [comment]
Only show left panel then? Or no screenshot? Also need to remember to update all images to reflect the latest version. This is missing the dashboard button.

**Comment by AllardQuek** [comment]
Full screenshot could be clearer. Can try
