### ISSUE TITLE
[PE-D] UG - Features: Purge Data

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103-F09-3/tp#348]
Could be phrased in a more straightforward way for the user. 

For example: Clears all data in PE. This can be used to delete pre-existing sample data or existing user data.

![Screenshot 2021-10-29 at 10.36.22 PM.png](https://raw.githubusercontent.com/mslevis/ped/main/files/4149825f-2344-4ca9-b7be-8d1637d34b34.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: mslevis/ped#7

**Comment by AllardQuek** [comment]
Good suggestion
