### ISSUE TITLE
-0 can be accepted as a lab score

### ISSUE THREAD

**Issue by shermannws** [AY2122S1-CS2103-F09-3/tp#368]
![image](https://user-images.githubusercontent.com/77196403/139574937-6bbe53c5-6ba4-46ab-96b3-248f62e69dfa.png)

**Comment by shermannws** [comment]
to be further reviewed after #390 is fixed

**Comment by reddevil1313** [comment]
> to be further reviewed after #390 is fixed

#390 is fixed now! 
Is -0 a valid input? currently, it inputs as 0.

Screenshot:
<img width="945" alt="Screenshot 2021-11-04 at 2 58 05 PM" src="https://user-images.githubusercontent.com/64184221/140270674-8bd4e05e-8111-44e2-9259-24e029c56fc5.png">
