### ISSUE TITLE
`AddLab`: bug for invalid total score and existing lab

### ISSUE THREAD

**Issue by AllardQuek** [AY2122S1-CS2103-F09-3/tp#408]
No error message returned when Lab 7 already exists. Command used: `addlab -ln 7 -ts 7-8`

![image](https://user-images.githubusercontent.com/40263305/139872080-d29a4dd7-19d0-4cc7-9e40-cba03a86a959.png)

**Comment by shermannws** [comment]
Interestingly, I saw your issue report and did a local test on the latest master branch. Error message was displayed on the UI for mine, do you have more detailed execution steps which i can try to follow to replicate the bug?

**Comment by AllardQuek** [comment]
Try with -ts 7-8 ? Let me try and screen record

**Comment by AllardQuek** [comment]
Yes I think that was on the command history branch, which was not updated

**Comment by AllardQuek** [comment]
Ignore!
