### ISSUE TITLE
Positive test cases in EditCommand does not work on Java CI

### ISSUE THREAD

**Issue by ZhaoPeiduo** [AY2122S1-CS2103-F09-3/tp#459]
After fixing issue #457 in #458 The following positive test cases in `EditCommandTest` pass on IntelliJ but not on Java CI:
- `execute_allFieldsSpecifiedUnfilteredList_success`
- `execute_someFieldsSpecifiedUnfilteredList_success`
- `execute_noFieldSpecifiedUnfilteredList_failure` 

A relevant post on forum is [here](https://github.com/nus-cs2103-AY2122S1/forum/issues/336) but I didnt encounter similar problem inside

**Comment by AllardQuek** [comment]
Duplicate? #443

**Comment by ZhaoPeiduo** [comment]
Oh yep
