### ISSUE TITLE
Verify font issue

### ISSUE THREAD

**Issue by AllardQuek** [AY2122S1-CS2103-F09-3/tp#466]
Suspect Courier font might not be displaying on some devices.

![telegram-cloud-photo-size-5-6066526072083689075-y](https://user-images.githubusercontent.com/40263305/140539839-ccbc3b6a-fc36-49d4-b496-61b8f7aa3de1.jpg)

**Comment by erwinqxy** [comment]
yes, the font only match for command but not the student list 

<img width="1204" alt="Screenshot 2021-11-06 at 12 20 33 PM" src="https://user-images.githubusercontent.com/72030222/140597659-40ba64f6-5cd2-41d3-9d85-8e31816d9178.png">

**Comment by erwinqxy** [comment]
Fix in https://github.com/AY2122S1-CS2103-F09-3/tp/pull/516
