### ISSUE TITLE
[DG] Refine manual testing instructions

### ISSUE THREAD

**Issue by AllardQuek** [AY2122S1-CS2103-F09-3/tp#471]
Could consider omitting how to test features (since there's already the UG), or refining further
![image](https://user-images.githubusercontent.com/40263305/140543639-dc69224a-c8a6-43dd-bdf2-830776c63b8b.png)

More info: https://nus-cs2103-ay2122s1.github.io/website/admin/tp-deliverables.html#deliverable-developer-guide-dg

**Comment by erwinqxy** [comment]
<img width="1132" alt="Screenshot 2021-11-07 at 11 53 58 PM" src="https://user-images.githubusercontent.com/72030222/140652202-3dbc190e-6e13-468e-9353-4804b39b5307.png">

need to update more ...

**Comment by AllardQuek** [comment]
Will add a couple of lines on how to test `upload`.
